title: Lewis Dryburgh
description: lewisdryburgh.com
theme: minima
baseurl: "/ldblog"
url: "https://lewdry.github.io"
minima:
  nav_pages:
    - blog.md
instagram_username: lewdry
linkedin_username: lewis-dryburgh