title: Lewis Dryburgh | Data Practitioner & Developer
tagline: Bridging the gap between public sector data and human-centred technology.
description: >
  Lewis Dryburgh is a Sydney-based developer and public sector practitioner specialising in data governance, digital transformation and human-centred tools like Artflip and Big Pause.
url: "https://lewisdryburgh.com"
baseurl: ""
author:
  name: Lewis Dryburgh
  twitter: lewdryburgh
social:
  name: Lewis Dryburgh
  links:
    - https://www.linkedin.com/in/lewis-dryburgh
    - https://github.com/lewdry
    - https://medium.com/@lewdry
theme: minima
minima:
  nav_pages:
    - projects.md
    - blog.md

collections:
  projects:
    output: true
    permalink: /projects/:name/
instagram_username: lewdry
linkedin_username: lewis-dryburgh
github_username: lewdry
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sitemap:
  exclude:
    - /assets/
    - /404.html